CREATE TABLE SG_TRACE_INDEX_SITE (
TI_SITE			VARCHAR2(4)	NOT NULL,
TI_MASQUE_COMPTEUR	NUMBER(1)	NOT NULL,
TI_PERIODE 		VARCHAR2(2)	NOT NULL,
TI_DATE_RELEVE		DATE		NOT NULL,
TI_EQUIPEMENT		VARCHAR2(5)	NOT NULL,
TI_TYPE_COMPTEUR	VARCHAR2(6)	NOT NULL,
TI_DATE			DATE		DEFAULT sysdate NOT NULL,
TI_NATURE_OPERATION	NUMBER(1)	NOT NULL,
TI_INDEX		NUMBER(15, 2)	DEFAULT 0	NOT NULL,
TI_COEF			NUMBER(6, 2)	DEFAULT 1	NOT NULL,
TI_QUANTITE		NUMBER(15, 2)	DEFAULT 0	NOT NULL,
TI_STATUT		NUMBER(1)	DEFAULT 1	NOT NULL,
TI_INDEX_PREC		NUMBER(15, 2)	DEFAULT 0	NOT NULL,
TI_OPERATEUR		VARCHAR2(30)	NOT NULL, 
CONSTRAINT TI_TRACE_PK	 PRIMARY KEY(TI_SITE, TI_MASQUE_COMPTEUR, TI_PERIODE, TI_DATE_RELEVE,
				     TI_EQUIPEMENT, TI_TYPE_COMPTEUR, TI_DATE, TI_NATURE_OPERATION)
)TABLESPACE USERS;

CREATE TABLE SG_TRACE_VALEUR_SITE (
TV_SITE			VARCHAR2(4)	NOT NULL,
TV_MASQUE_DONNEE	NUMBER(1)	NOT NULL,
TV_PERIODE		VARCHAR2(2)	NOT NULL,
TV_DATE_RELEVE		DATE		NOT NULL,
TV_EQUIPEMENT		VARCHAR2(5)	NOT NULL,
TV_TYPE_DONNEE		VARCHAR2(8)	NOT NULL,
TV_DATE DATE		DEFAULT sysdate NOT NULL,
TV_NATURE_OPERATION	NUMBER(1)	NOT NULL,
TV_QUANTITE		NUMBER(15, 2)	DEFAULT 0	NOT NULL,
TV_QUANTITE_PREC	NUMBER(15, 2)	DEFAULT 0	NOT NULL, 
TV_OPERATEUR		VARCHAR2(30)	NOT NULL, 
CONSTRAINT TV_TRACE_PK	 PRIMARY KEY(TV_SITE, TV_MASQUE_DONNEE, TV_PERIODE, TV_DATE_RELEVE, 
				     TV_EQUIPEMENT, TV_TYPE_DONNEE, TV_DATE, TV_NATURE_OPERATION)
)TABLESPACE USERS;

CREATE PUBLIC SYNONYM SG_TRACE_INDEX_SITE FOR SG_TRACE_INDEX_SITE;
CREATE PUBLIC SYNONYM SG_TRACE_VALEUR_SITE FOR SG_TRACE_VALEUR_SITE;

CREATE ROLE SIG_MAJ_PRODUCTION_SAISIE  NOT IDENTIFIED; 
CREATE ROLE SIG_MAJ_PRODUCTION_TRACE   NOT IDENTIFIED; 
CREATE ROLE SIG_CTRL_PRODUCTION_SAISIE NOT IDENTIFIED; 

GRANT SIG_CONSUL_PRODUCTION_SAISIE TO SIG_CTRL_PRODUCTION_SAISIE;

GRANT SELECT ON SG_TRACE_INDEX_SITE  TO SIG_MAJ_PRODUCTION_SAISIE;
GRANT SELECT ON SG_TRACE_VALEUR_SITE TO SIG_MAJ_PRODUCTION_SAISIE;

GRANT INSERT ON SG_TRACE_INDEX_SITE  TO SIG_MAJ_PRODUCTION_SAISIE;
GRANT INSERT ON SG_TRACE_VALEUR_SITE TO SIG_MAJ_PRODUCTION_SAISIE;

GRANT UPDATE ON SG_TRACE_INDEX_SITE  TO SIG_MAJ_PRODUCTION_SAISIE;
GRANT UPDATE ON SG_TRACE_VALEUR_SITE TO SIG_MAJ_PRODUCTION_SAISIE;

REM GRANT DELETE ON SG_TRACE_INDEX_SITE  TO SIG_MAJ_PRODUCTION_SAISIE;
REM GRANT DELETE ON SG_TRACE_VALEUR_SITE TO SIG_MAJ_PRODUCTION_SAISIE;
GRANT DELETE ON SG_TRACE_INDEX_SITE  TO SIG_MAJ_PRODUCTION_TRACE;
GRANT DELETE ON SG_TRACE_VALEUR_SITE TO SIG_MAJ_PRODUCTION_TRACE;

