insert into sgc_vente values('NBFN','1','nombre de factures normales');
insert into sgc_vente values('NBFC','1','nombre de factures complémentaires');
insert into sgc_vente values('NBFA','1','nombre de factures d''arrêt');
insert into sgc_vente values('NBFR','1','nombre de factures rectificatives');
insert into sgc_vente values('NBFF','1','nombre de factures fraudes');
insert into sgc_vente values('NBVE','1','nombre de ventes enregistrées');
insert into sgc_vente values('QT1','2','kWh tranche 1');
insert into sgc_vente values('QT2','2','kWh tranche 2');
insert into sgc_vente values('QT3','2','kWh tranche 3');
insert into sgc_vente values('QT4','2','kWh tranche 4');
insert into sgc_vente values('MT1','3','montant tranche 1');
insert into sgc_vente values('MT2','3','montant tranche 2');
insert into sgc_vente values('MT3','3','montant tranche 3');
insert into sgc_vente values('MT4','3','montant tranche 4');
insert into sgc_vente values('QHPL','2','kWh heures pleines');
insert into sgc_vente values('QHPO','2','kWh heures pointes');
insert into sgc_vente values('MTPL','3','montant heures pleines');
insert into sgc_vente values('MTPO','3','montant heures pointes');
insert into sgc_vente values('MREDEV','3','montant redevance compteur');
insert into sgc_vente values('MPOSTE','3','montant location poste');
insert into sgc_vente values('MPRIFIX','3','montant prime fixe');
insert into sgc_vente values('MPENAL','3','montant de la pénalité');
insert into sgc_vente values('MTAXTV','3','montant de la taxe TV (TSDAAE)');
insert into sgc_vente values('MTVA','3','montant de la TVA');
