insert into sgc_type_donnee values('PMAXICE','1','kW ','puissance maxi cent','puissance maximum journalière de la centrale ');
insert into sgc_type_donnee values('PMAXIRE','6','kW ','puissance maxi rés.','puissance maximum journalière du réseau');
insert into sgc_type_donnee values('HPMAXIC','1','hr','heure puis. maxi. cent.','heure ou a été atteinte la puissance maximum de la centrale');
insert into sgc_type_donnee values('HPMAXIR','6','hr','heure puis. maxi. rés.','heure ou a été atteinte la puissance maximum du réseau');
insert into sgc_type_donnee values('HPMINIR','6','hr','heure puis. mini.  rés.','heure de la puissance minimum du réseau');
insert into sgc_type_donnee values('HPMINIC','1','hr','heure puis. mini.  cent.','heure de la puissance minimum de la centrale');
insert into sgc_type_donnee values('PMINICE','1','kW ','puissance minimum cent.','puissance minimum journalière de la centrale ');
insert into sgc_type_donnee values('PMINIRE','6','kW ','puissance minimum rés.','puissance minimum journalière du réseau');
insert into sgc_type_donnee values('STODDO','2','L','stock DDO','stock de DDO de la centrale en litre');
insert into sgc_type_donnee values('RECDDO','2','L','réception DDO','quantité de DDO réceptionnée au cours des 24 dernières heures');
insert into sgc_type_donnee values('CESDDO','2','L','cession DDO','quantité de DDO cédée au cours des 24 dernières heures');
insert into sgc_type_donnee values('STOCFO','2','L','stock FO','stock de FO de la centrale en litre');
insert into sgc_type_donnee values('RECEFO','2','L','réception FO','quantité de FO réceptionnée au cours des 24 dernières heures');
insert into sgc_type_donnee values('CESSFO','2','L','cession FO','quantité de FO cédée au cours des 24 dernières heures');
insert into sgc_type_donnee values('STCHUI','2','L','stock huile citerne','stock d''huile dans les citernes de la centrale en litre');
insert into sgc_type_donnee values('STFHUI','2','fût','stock huile fût 200 l','quantité de fût d''huile en stock exprimée en nombre de fûts');
insert into sgc_type_donnee values('REFHUI','2','fût','réception fût huile','nombre de fûts réceptionnée au cours des 24 dernières heures');
insert into sgc_type_donnee values('CEFHUI','2','fût','cession fût huile','nombre de fûts d''huile cédée au cours des 24 dernières heures');
insert into sgc_type_donnee values('CONDDO','3','L','conso. DDO','consommation journalière de DDO du groupe');
insert into sgc_type_donnee values('CONSFO','3','L','conso. FO','consommation journalière de FO du groupe');
insert into sgc_type_donnee values('CONHUI','3','L','conso. huile','consommation journalière d''huile du groupe');
insert into sgc_type_donnee values('DEFDIE','5','heure','temps indis. entre.','centrale déficit de disponibilité sur entretiens');
insert into sgc_type_donnee values('DEFDII','5','heure','temps indis. incident','centrale déficit de disponibilité sur incidents');
insert into sgc_type_donnee values('IPRENL','5','MWh','ENL incident prod.','centrale énergie non livrée (ENL) sur incident de production');
insert into sgc_type_donnee values('IPRNCO','5','Nbre','nbre coupure inc.pro','centrale nombre de coupures sur incident de production');
insert into sgc_type_donnee values('IPRTCO','5','heure','temps coupure inc.pro','centrale temps total de coupures sur incident de production');
insert into sgc_type_donnee values('ITRENL','5','MWh','ENL incident trav.','centrale énergie non livrée (ENL) sur incident de travaux');
insert into sgc_type_donnee values('ITRNCO','5','Nbre','nbre coupure travaux','centrale nombre de coupures pour cause de travaux');
insert into sgc_type_donnee values('ITRTCO','5','heure','temps coupure travaux','centrale temps total de coupures pour cause de travaux');
insert into sgc_type_donnee values('IREENL','5','MWh','ENL incident réseau','centrale énergie non livrée (ENL) sur incident réseau');
insert into sgc_type_donnee values('IRENCO','5','Nbre','nbre coupure inc.rés','centralenombre de coupures sur incident de réseau');
insert into sgc_type_donnee values('IRETCO','5','heure','temps coupure inc.rés','centrale temps total de coupures sur incident de réseau');
insert into sgc_type_donnee values('DEINRT','5','Nbre','décl.n''affec.pas RT','déclenchement interne n''affectant pas le réseau de transport');
insert into sgc_type_donnee values('DEIORT','5','Nbre','décl. affectant RT','déclenchement interne affectant le réseau de transport');
insert into sgc_type_donnee values('DECERT','5','Nbre','décl. RT causes exté.','déclenchements du réseau de transport cause extérieure');
insert into sgc_type_donnee values('NIVPLU','4','mm','hauteur des pluies','hauteur des pluies exprimé en millimètres');
insert into sgc_type_donnee values('CAMCEN','4','m','cote amont barrage','cote amont du barrageexprimée en mètres');
insert into sgc_type_donnee values('CAVCEN','4','m','cote aval barrage','cote aval de la centrale exprimée en mètres');
insert into sgc_type_donnee values('VOLEAU','4','10^6m3','volume eau réserve','volume d''eau de la réserve exprimé en millions de m3');
insert into sgc_type_donnee values('VEAUIR','4','10^6m3','volume eau irrigation','volume d''eau prélevé pour l''irrigation exprimé en millions de m3');
insert into sgc_type_donnee values('VEAUDE','4','10^6m3','volume eau déversé','volume d''eau déversé exprimé en millions de m3');
insert into sgc_type_donnee values('VEAUEV','4','10^6m3','volume eau évaporé','volume d''eau évaporé exprimé en millions de m3');
insert into sgc_type_donnee values('VEAUTU','4','10^6m3','volume eau turbiné','volume d''eau turbiné exprimé en millions de m3');
insert into sgc_type_donnee values('EEPROD','4','GWh','énergie élec. produc.','énergie électique productible compte tenu réserve d''eau');
insert into sgc_type_donnee values('NBAVAR','0','nbre','nbre avaries','nombre d''avaries répertoriées à la centrale');
insert into sgc_type_donnee values('NBDIGE','0','nbre','nbre disjonc. géné.','centrale nombre de disjonctions générales');
insert into sgc_type_donnee values('NBDIPA','0','nbre','nbre disjonc. partiel.','centrale nombre de disjonctions partielles');
insert into sgc_type_donnee values('NBACTR','0','nbre','nbre accidents trav.','nombre d''accidents de travail');

